server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR}:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    virtual-host-name: cassandra-sidecar.vip

sidecar:
  port: 9042