server:
  port: 9090

spring:
  application:
    name: cassandra-sidecar

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # enable these two settings if you want discovery to work
    registerWithEureka: true
    fetchRegistry: true
    instance:
      virtual-host-name: cassandra-sidecar.vip
      preferIpAddress: true

sidecar:
  port: 9042