server:
  port: 8080

spring:
  application:
    name: user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # enable these two settings if you want discovery to work
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true