server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR}:8761/eureka/
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    preferIpAddress: true

cassandra:
  clusterName: cassandra-sidecar.vip
  keyspace: manager
  cqlPort: 9042