config-server:
  build: ./config-server
  ports:
    - "8888:8888"

eureka:
  build: ./eureka
  ports:
    - "8761:8761"

cassandra:
  image: cassandra:2
  links:
   - eureka
  ports:
   - "9042"

cassandra-sidecar:
  build: ./cassandra-sidecar
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - cassandra
  ports:
    - "9090"

user:
  build: ./user
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - cassandra-sidecar
  ports:
    - "8080:8080"