# general spring settings
spring:
  application:
    name: user
  profiles:
    default: development
    active: development

cassandra:
  clusterName: cassandra-sidecar.vip
  keyspace: manager
  overrideEurekaLookup: true
  cqlPort: 9042
  contactPoints:
    - localhost

eureka:
  # these are settings for the client that gets services
  client:
    # enable these two settings if you want discovery to work
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # this describes the actual instance that is registered and parameters around it
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true